loki:
  persistence:
    enabled: false

timescaledb-single:
  persistentVolumes:
    data:
      enabled: false
    wal:
      enabled: false

victoria-metrics-single:
  server:
    persistentVolume:
      enabled: false