---
k8sWatcher:
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

portal:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 300m
      memory: 256Mi

clickhouse:
  resources:
    requests:
      cpu: 1000m
      memory: 4Gi
    limits:
      memory: 12Gi

opentelemetry-collector:
  replicaCount: 3
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 1200m
      memory: 2048Mi

victoria-metrics-agent:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 1Gi

metrics-ingester:
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

custom-metrics:
  extraArgs:
    remoteWrite.maxHourlySeries: "10000000"
    remoteWrite.maxDailySeries: "100000000"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1500m
      memory: 2Gi

victoria-metrics-single:
  server:
    resources:
      requests:
        cpu: 1000m
        memory: 5000Mi
      limits:
        memory: 6Gi
