---
k8sWatcher:
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

portal:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 256Mi

clickhouse:
  resources:
    requests:
      cpu: 1000m
      memory: 4Gi
    limits:
      memory: 12Gi

opentelemetry-collector:
  replicaCount: 3
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      memory: 2048Mi

victoria-metrics-agent:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 1Gi

metrics-ingester:
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      memory: 1Gi

custom-metrics:
  extraArgs:
    remoteWrite.maxHourlySeries: "10000000"
    remoteWrite.maxDailySeries: "100000000"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 2Gi

victoria-metrics-single:
  server:
    resources:
      requests:
        cpu: 1000m
        memory: 5000Mi
      limits:
        memory: 6Gi

monitors-manager:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi 
    limits:
      memory: 512Mi


backend:
  postgresql:
    primary:
      resources:
        requests:
          cpu: 90m
          memory: 200Mi
        limits:
          memory: 400Mi