---
agent:
  alligator:
    resources:
      requests:
        cpu: 200m
        memory: 250Mi
      limits:
        cpu: 200m
        memory: 250Mi
  tracy:
    resources:
      requests:
        cpu: 250m
        memory: 750Mi
      limits:
        cpu: 250m
        memory: 750Mi